### ISSUE TITLE
zstd TestEncoderRegression tests fail: appear to deadlock

### ISSUE THREAD

**Issue by glycerine** [klauspost/compress#1034]
In zstd/ one or more of the TestEncoderRegression tests appears to deadlock. 

I see this on macOS and on linux.
Go version 1.23.3 on amd64 on both.

This was at the latest master branch as of this writing, b08929a7ab40b53c9115029ae86d79fcd1f25b4c

On macOS, the deadlocked test was TestEncoderRegression/fastest-c1-w16384k-nolit/9c8bf96988aa1f38225c6590e68d5546e8139c8e

On Linux, the deadlocked test was TestEncoderRegression/default-c1-w4096k-nocrc/5207e175e4dd2f2084c580efda72fdfdcd219007

run logs:
~~~
on macOS:
$ go test -v -timeout 0
=== RUN   TestHeader_Decode
=== RUN   TestHeader_Decode/0
=== RUN   TestHeader_Decode/1
=== RUN   TestHeader_Decode/2
=== RUN   TestHeader_Decode/3
=== RUN   TestHeader_Decode/4

... lots of passing tests omitted...

=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/80a461e7ef816d88833a9446fe10fb950936fab6
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/7680ed8dbba4ec8b2b21737cae03103e059672bf
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/b0bf22f5addfa262a8c8f980c4de1c885c50592e
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/5b6db6424de2d6124d5b1a331d26e3d3a008e999
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/9dada113da95da6ea06236d9f77269d83ae2f837
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/c3a4da40e5ca988970b6a574b6ed62733a95e414
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/8423cde21da166d42f140074e323bd2d2c877571
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/f00bb5d1d786a797ebfa354012134c427200fe48
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/bde47981884d9d452a4bad9fb22ec3cdf832eae2
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/d9927e965cf0930ddda2196645f4e6837b3d6d25
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/7135cc5e5610c0c0c6d1c245eb47739a29b0e01d
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/581d5cc43f75e203c5d49aa473c060419fb4891d
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/2a725169e4a9debb249140d56da035d44623858c
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/430af2cbc00daa8e8fad04cf13d97a3877ef3baa
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/1db4505f4d4be30a89aeb140910ada446080ccd6
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/5d11e6bd5db3af265599e68dff76c13320a82cda
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/0e9804778124c62c4ee575482f422b6c711e774d
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/ec2dcebd55e6d6b0322aeecaf18d88f95ef05acb
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/76d4b423697e0194e388a03e4dba1b86ec2b457e
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/4b1179d0397d59173f05dcfceafb97d5ea31ba84
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/c91161c3eadef17a09daa392f1098f0a269b0dd0
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/6d970451935caed62e9d98ed75eecb92d77422f3
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/3c297831e73b052d5efc6f73d7f9aa3544301534
2024/12/29 20:20:57 === Timeout, assuming deadlock ===
*** goroutine dump...
goroutine 28440 [running]:
github.com/klauspost/compress/zstd.timeout.func2()
	/Users/jaten/go/src/github.com/klauspost/compress/zstd/decoder_test.go:2159 +0x8d
created by github.com/klauspost/compress/zstd.timeout in goroutine 28439
	/Users/jaten/go/src/github.com/klauspost/compress/zstd/decoder_test.go:2153 +0x8e

goroutine 1 [chan receive, 4 minutes]:
testing.(*T).Run(0xc0001124e0, {0x49ce935?, 0x1f?}, 0x4a92e20)
	/usr/local/go/src/testing/testing.go:1751 +0x3ab
testing.runTests.func1(0xc0001124e0)
	/usr/local/go/src/testing/testing.go:2168 +0x37
testing.tRunner(0xc0001124e0, 0xc00009abe8)
	/usr/local/go/src/testing/testing.go:1690 +0xf4
testing.runTests(0xc00011c030, {0x4c26040, 0x44, 0x44}, {0x3ff0000000000000?, 0x1?, 0x0?})
	/usr/local/go/src/testing/testing.go:2166 +0x43d
testing.(*M).Run(0xc00014e000)
	/usr/local/go/src/testing/testing.go:2034 +0x64a
github.com/klauspost/compress/zstd.TestMain(0xc00014e000)
	/Users/jaten/go/src/github.com/klauspost/compress/zstd/zstd_test.go:28 +0x6f
main.main()
	_testmain.go:269 +0xa8

goroutine 28439 [chan receive]:
testing.(*T).Run(0xc000112820, {0xc000621470?, 0x0?}, 0xc046652210)
	/usr/local/go/src/testing/testing.go:1751 +0x3ab
github.com/klauspost/compress/zstd.TestEncoderRegression(0xc000112820)
	/Users/jaten/go/src/github.com/klauspost/compress/zstd/encoder_test.go:229 +0x17a
testing.tRunner(0xc000112820, 0x4a92e20)
	/usr/local/go/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1743 +0x390

goroutine 74431 [syscall]:
syscall.syscall(0x4843646?, 0xc003b2bf80?, 0x80000000000?, 0x7ffff80000000000?)
	/usr/local/go/src/runtime/sys_darwin.go:27 +0x58
syscall.write(0xc00010e060?, {0xc0021e40e0?, 0x28?, 0xc001b11c10?})
	/usr/local/go/src/syscall/zsyscall_darwin_amd64.go:1709 +0x45
syscall.Write(...)
	/usr/local/go/src/syscall/syscall_unix.go:211
internal/poll.ignoringEINTRIO(...)
	/usr/local/go/src/internal/poll/fd_unix.go:745
internal/poll.(*FD).Write(0xc00010e060, {0xc0021e40e0, 0x62, 0x70})
	/usr/local/go/src/internal/poll/fd_unix.go:381 +0x394
os.(*File).write(...)
	/usr/local/go/src/os/file_posix.go:46
os.(*File).Write(0xc000100010, {0xc0021e40e0?, 0x62, 0xc001b11e88?})
	/usr/local/go/src/os/file.go:195 +0x51
fmt.Fprintf({0x4a959f8, 0xc000100010}, {0x49cba23, 0xd}, {0xc001b11e88, 0x1, 0x1})
	/usr/local/go/src/fmt/print.go:225 +0x97
testing.(*chattyPrinter).Updatef(0xc003a4f920?, {0xc003a4f920?, 0xc0000d7170?}, {0x49cba23?, 0x3a233c8?}, {0xc001b11e88, 0x1, 0x1})
	/usr/local/go/src/testing/testing.go:570 +0x1a5
testing.(*T).Run(0xc0005b2340, {0xc0000d7170?, 0xc045e9e6f0?}, 0xc003683360)
	/usr/local/go/src/testing/testing.go:1734 +0x2c5
github.com/klauspost/compress/zstd.TestEncoderRegression.func1(0xc0005b2340)
	/Users/jaten/go/src/github.com/klauspost/compress/zstd/encoder_test.go:251 +0x2ea
testing.tRunner(0xc0005b2340, 0xc046652210)
	/usr/local/go/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 28439
	/usr/local/go/src/testing/testing.go:1743 +0x390

goroutine 15070 [chan receive, 4 minutes]:
testing.(*T).Parallel(0xc046e48340)
	/usr/local/go/src/testing/testing.go:1484 +0x215
github.com/klauspost/compress/zstd.TestDecoderRawDict(0xc046e48340)
	/Users/jaten/go/src/github.com/klauspost/compress/zstd/dict_test.go:613 +0x39
testing.tRunner(0xc046e48340, 0x4a92dd8)
	/usr/local/go/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1743 +0x390

*** end
=== RUN   TestEncoderRegression/fastest-c1-w16384k-nolit/9c8bf96988aa1f38225c6590e68d5546e8139c8e
exit status 2
FAIL	github.com/klauspost/compress/zstd	320.301s
jaten@jbook ~/go/src/github.com/klauspost/compress/zstd (master) $ go version
go version go1.23.3 darwin/amd64
jaten@jbook ~/go/src/github.com/klauspost/compress/zstd (master) $ git log|head -20
commit b08929a7ab40b53c9115029ae86d79fcd1f25b4c
Author: Hyunsoo Shin (Lake) <hyunsooda@kaist.ac.kr>
Date:   Fri Dec 20 19:14:25 2024 +0900

    docs: Description typo fixed (#1031)

commit bbaf27d0c3d903219116b582df91a62434837f89
Author: alingse <alingse@foxmail.com>
Date:   Mon Dec 16 20:57:14 2024 +0800

    zstd: fix: check `r.err != nil` but return a nil value error `err` (#1028)
    
    * fix: check `r.err != nil` but return a nil value error `err`
    
    Signed-off-by: alingse <alingse@foxmail.com>
    
    * fix: check `r.err != nil` but return a nil value error `err`
    
    Signed-off-by: alingse <alingse@foxmail.com>
    
jaten@jbook ~/go/src/github.com/klauspost/compress/zstd (master) $
~~~

linux:
~~~
$ go test -v -timeout 0
=== RUN   TestHeader_Decode
=== RUN   TestHeader_Decode/0
=== RUN   TestHeader_Decode/1
=== RUN   TestHeader_Decode/2
=== RUN   TestHeader_Decode/3
=== RUN   TestHeader_Decode/4
=== RUN   TestHeader_Decode/5
=== RUN   TestHeader_Decode/6
=== RUN   TestHeader_Decode/7
=== RUN   TestHeader_Decode/8

... lots of passing tests omitted...

=== RUN   TestEncoderRegression/default-c1-w4096k-nocrc/72734767d70a55c5b2f565c36bbb3e4f98779928
=== RUN   TestEncoderRegression/default-c1-w4096k-nocrc/20c5754453ba89d0a5985fd51fe6d811f11fbc99
=== RUN   TestEncoderRegression/default-c1-w4096k-nocrc/db1555cec708aa0cbed90eee687a6f8134cb0c51
=== RUN   TestEncoderRegression/default-c1-w4096k-nocrc/f6dfd9b844d95ff0231dfc801a81f6f528fcd87a
=== RUN   TestEncoderRegression/default-c1-w4096k-nocrc/ea34071ff9b76cc4534879508ec34eba63d71920
=== RUN   TestEncoderRegression/default-c1-w4096k-nocrc/92807c81615ebbb4055984f6dca2c3a93d19118f
=== RUN   TestEncoderRegression/default-c1-w4096k-nocrc/66a4927f047559baffc64fb3a668f43cd40837d5
2024/12/29 14:19:40 === Timeout, assuming deadlock ===
*** goroutine dump...
goroutine 17945 [running]:
github.com/klauspost/compress/zstd.timeout.func2()
	/home/jaten/go/src/github.com/klauspost/compress/zstd/decoder_test.go:2159 +0x8d
created by github.com/klauspost/compress/zstd.timeout in goroutine 17944
	/home/jaten/go/src/github.com/klauspost/compress/zstd/decoder_test.go:2153 +0x8e

goroutine 1 [chan receive, 4 minutes]:
testing.(*T).Run(0xc0000ec4e0, {0x6cf67e?, 0x0?}, 0x6de9c8)
	/usr/local/go1.23.3/src/testing/testing.go:1751 +0x3ab
testing.runTests.func1(0xc0000ec4e0)
	/usr/local/go1.23.3/src/testing/testing.go:2168 +0x37
testing.tRunner(0xc0000ec4e0, 0xc0000e2be8)
	/usr/local/go1.23.3/src/testing/testing.go:1690 +0xf4
testing.runTests(0xc000010198, {0x8c2420, 0x44, 0x44}, {0x3ff0000000000000?, 0x1?, 0x0?})
	/usr/local/go1.23.3/src/testing/testing.go:2166 +0x43d
testing.(*M).Run(0xc0000f00a0)
	/usr/local/go1.23.3/src/testing/testing.go:2034 +0x64a
github.com/klauspost/compress/zstd.TestMain(0xc0000f00a0)
	/home/jaten/go/src/github.com/klauspost/compress/zstd/zstd_test.go:28 +0x6f
main.main()
	_testmain.go:269 +0xa8

goroutine 15263 [chan receive, 4 minutes]:
testing.(*T).Parallel(0xc0015c7a00)
	/usr/local/go1.23.3/src/testing/testing.go:1484 +0x215
github.com/klauspost/compress/zstd.TestDecoderRawDict(0xc0015c7a00)
	/home/jaten/go/src/github.com/klauspost/compress/zstd/dict_test.go:613 +0x39
testing.tRunner(0xc0015c7a00, 0x6de980)
	/usr/local/go1.23.3/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/usr/local/go1.23.3/src/testing/testing.go:1743 +0x390

goroutine 198630 [syscall]:
syscall.Syscall(0x1, 0x1, 0xc0038b40c0, 0x61)
	/usr/local/go1.23.3/src/syscall/syscall_linux.go:73 +0x25
syscall.write(0xc0000d2120?, {0xc0038b40c0?, 0x28?, 0xc0000dfc10?})
	/usr/local/go1.23.3/src/syscall/zsyscall_linux_amd64.go:964 +0x3b
syscall.Write(...)
	/usr/local/go1.23.3/src/syscall/syscall_unix.go:211
internal/poll.ignoringEINTRIO(...)
	/usr/local/go1.23.3/src/internal/poll/fd_unix.go:745
internal/poll.(*FD).Write(0xc0000d2120, {0xc0038b40c0, 0x61, 0xc0})
	/usr/local/go1.23.3/src/internal/poll/fd_unix.go:381 +0x394
os.(*File).write(...)
	/usr/local/go1.23.3/src/os/file_posix.go:46
os.(*File).Write(0xc0000b2098, {0xc0038b40c0?, 0x61, 0xc0000dfe88?})
	/usr/local/go1.23.3/src/os/file.go:195 +0x51
fmt.Fprintf({0x72af40, 0xc0000b2098}, {0x6cc679, 0xd}, {0xc0000dfe88, 0x1, 0x1})
	/usr/local/go1.23.3/src/fmt/print.go:225 +0x97
testing.(*chattyPrinter).Updatef(0xc003b0fbc0?, {0xc003b0fbc0?, 0xc00072c990?}, {0x6cc679?, 0x3610c78?}, {0xc0000dfe88, 0x1, 0x1})
	/usr/local/go1.23.3/src/testing/testing.go:570 +0x1a5
testing.(*T).Run(0xc003cbe1a0, {0xc00072c990?, 0xc0467a0f60?}, 0xc0008245e0)
	/usr/local/go1.23.3/src/testing/testing.go:1734 +0x2c5
github.com/klauspost/compress/zstd.TestEncoderRegression.func1(0xc003cbe1a0)
	/home/jaten/go/src/github.com/klauspost/compress/zstd/encoder_test.go:251 +0x2ea
testing.tRunner(0xc003cbe1a0, 0xc00398c120)
	/usr/local/go1.23.3/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 17944
	/usr/local/go1.23.3/src/testing/testing.go:1743 +0x390

goroutine 17944 [chan receive]:
testing.(*T).Run(0xc0000ec680, {0xc0017fc5d0?, 0x0?}, 0xc00398c120)
	/usr/local/go1.23.3/src/testing/testing.go:1751 +0x3ab
github.com/klauspost/compress/zstd.TestEncoderRegression(0xc0000ec680)
	/home/jaten/go/src/github.com/klauspost/compress/zstd/encoder_test.go:229 +0x17a
testing.tRunner(0xc0000ec680, 0x6de9c8)
	/usr/local/go1.23.3/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 1
	/usr/local/go1.23.3/src/testing/testing.go:1743 +0x390

*** end
=== RUN   TestEncoderRegression/default-c1-w4096k-nocrc/5207e175e4dd2f2084c580efda72fdfdcd219007
exit status 2
FAIL	github.com/klauspost/compress/zstd	274.578s
jaten@rog ~/go/src/github.com/klauspost/compress/zstd (master) $ go version
go version go1.23.3 linux/amd64
jaten@rog ~/go/src/github.com/klauspost/compress/zstd (master) $ git log|head -20
commit b08929a7ab40b53c9115029ae86d79fcd1f25b4c
Author: Hyunsoo Shin (Lake) <hyunsooda@kaist.ac.kr>
Date:   Fri Dec 20 19:14:25 2024 +0900

    docs: Description typo fixed (#1031)

commit bbaf27d0c3d903219116b582df91a62434837f89
Author: alingse <alingse@foxmail.com>
Date:   Mon Dec 16 20:57:14 2024 +0800

    zstd: fix: check `r.err != nil` but return a nil value error `err` (#1028)
    
    * fix: check `r.err != nil` but return a nil value error `err`
    
    Signed-off-by: alingse <alingse@foxmail.com>
    
    * fix: check `r.err != nil` but return a nil value error `err`
    
    Signed-off-by: alingse <alingse@foxmail.com>
~~~

**Comment by glycerine** [comment]
I tried backing up to the last tagged release, v1.17.11. This did not help. I still get reports of deadlock on the zstd/TestEncoderRegression tests after 4 minutes+ of running.

**Comment by klauspost** [comment]
Both your tests are stopped printing to stdout, so it seems like it is very slow at writing to your console.

Maybe try omitting `-v`, or use `-short` if your system is slow. On my machine, it completes in ~1.5m with `-v`.

**Comment by glycerine** [comment]
Ah, thanks. Sorry to bother you with this then. It's probably just emacs not keeping up with trying to do some regex matching or some scanning on the shell inside it. They do seem to be making emacs slower over time. In point of fact, the tests complete just fine when I write to a log file instead of the terminal inside emacs; in 2m39s without -v (but wow your machine must be very fast to finish in 1.5m).
