### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by bronze1man** [klauspost/compress#217]
My server crash after 10-20 min after start.
caller code:
```go
var gCompressPool5 sync.Pool
func mustFlateCompressWithBufferToBufWPool5(inb []byte,bufW *bytes.Buffer) {
	var flateW *flate.Writer
	obj:=gCompressPool5.Get()
	if obj==nil{
		var err error
		flateW,err = flate.NewWriter(bufW,4)
		if err!=nil{
			panic(err)
		}
	}else{
		flateW = obj.(*flate.Writer)
		flateW.Reset(bufW)
	}
	_, err := flateW.Write(inb)
	if err != nil {
		flateW.Close()
		flateW.Reset(nil)
		gCompressPool5.Put(flateW)
		panic(err)
	}
	err = flateW.Close()
	flateW.Reset(nil)
	gCompressPool5.Put(flateW)
	if err != nil {
		panic(err)
	}
}
```

```
runtime error: slice bounds out of range

goroutine 82 [running]:
github.com/klauspost/compress/flate.(*fastGen).matchlenLong(0xc0288e8000, 0x5386ca610003395c, 0xc028aea000, 0x3fffc, 0x100000, 0x13)
	github.com/klauspost/compress/flate/fast_encoder.go:208 +0xb6
github.com/klauspost/compress/flate.(*fastEncL4).Encode(0xc0288e8000, 0xc02bcf2090, 0xc02bf88000, 0xffff, 0xffff)
	github.com/klauspost/compress/flate/level4.go:127 +0x4db
github.com/klauspost/compress/flate.(*compressor).storeFast(0xc02bcf2000)
	github.com/klauspost/compress/flate/deflate.go:590 +0x1c1
github.com/klauspost/compress/flate.(*compressor).write(0xc02bcf2000, 0xc02176bffc, 0x1c80ae, 0x18a004, 0x113d380, 0xc007352960, 0xc007352960)
	github.com/klauspost/compress/flate/deflate.go:614 +0x81
github.com/klauspost/compress/flate.(*Writer).Write(0xc02bcf2000, 0xc02172c000, 0x1c80ae, 0x1ca000, 0xc000d2b568, 0x44b894, 0xc015512199)
	github.com/klauspost/compress/flate/deflate.go:781 +0x4b
...
```

I have tried a single thread, it crash like this too(after one hour):
```go
var gCompressWriter *flate.Writer
var gCompressWriterLocker sync.Mutex
func mustFlateCompressWithBufferToBufWPool3(inb []byte,bufW *bytes.Buffer) {
	gCompressWriterLocker.Lock()
	defer gCompressWriterLocker.Unlock()
	if gCompressWriter==nil{
		var err error
		gCompressWriter,err = flate.NewWriter(bufW,4)
		if err!=nil{
			panic(err)
		}
	}else{
		gCompressWriter.Reset(bufW)
	}
	_, err := gCompressWriter.Write(inb)
	if err != nil {
		gCompressWriter.Close()
		gCompressWriter.Reset(nil)
		panic(err)
	}
	err = gCompressWriter.Close()
	gCompressWriter.Reset(nil)
	if err != nil {
		panic(err)
	}
}
```

I have tried flate from golang 1.11.6, it never crash after 3 hours. (but use more cpu resource than this library)
I have tried flate from https://github.com/klauspost/compress and do not reuse the writer object, it never crash after 12 hours.(but use more cpu resource) 

Workaround right now: use flate from golang 1.11.6 and sync.Pool

**Comment by bronze1man** [comment]
When I set debugDecode to true, I got:
```
panic: t >=s:2147411689 14691

goroutine 60 [running]:
github.com/klauspost/compress/flate.(*fastGen).matchlenLong(0xc0356e0000, 0x7ffee6e900003963, 0xc03583c000, 0x78c4, 0x100000, 0x46)
	github.com/klauspost/compress/flate/fast_encoder.go:195 +0x596
github.com/klauspost/compress/flate.(*fastEncL4).Encode(0xc0356e0000, 0xc034f6a090, 0xc0357e2000, 0x78c4, 0xffff)
	github.com/klauspost/compress/flate/level4.go:127 +0x4db
github.com/klauspost/compress/flate.(*compressor).storeFast(0xc034f6a000)
	github.com/klauspost/compress/flate/deflate.go:590 +0x1c1
github.com/klauspost/compress/flate.(*compressor).close(0xc034f6a000, 0x0, 0x0)
	github.com/klauspost/compress/flate/deflate.go:715 +0x4e
github.com/klauspost/compress/flate.(*Writer).Close(0xc034f6a000, 0xc02aca8000, 0x78c4)
	github.com/klauspost/compress/flate/deflate.go:801 +0x2d
```

**Comment by klauspost** [comment]
Thanks for the detail report. I will take a look at the issue.

**Comment by klauspost** [comment]
My guess is that you are running a lot of very small buffers through this, correct?

Could you try out #218 - that could likely fix it?

**Comment by klauspost** [comment]
I managed to reproduce it with a test which indicates this should help out, but please do give feedback on whether it also helps you.

**Comment by bronze1man** [comment]
another crash stack from master branch. (not from #218 )
```
panic: runtime error: slice bounds out of range

goroutine 90 [running]:
github.com/klauspost/compress/flate.(*fastEncL4).Encode(0xc03089e000, 0xc0320c2090, 0xc02a4aa000, 0x8cc5, 0xffff)
        github.com/klauspost/compress/flate/level4.go:111 +0x9f4
github.com/klauspost/compress/flate.(*compressor).storeFast(0xc0320c2000)
        github.com/klauspost/compress/flate/deflate.go:590 +0x1c1
github.com/klauspost/compress/flate.(*compressor).close(0xc0320c2000, 0x0, 0x0)
        github.com/klauspost/compress/flate/deflate.go:715 +0x4e
github.com/klauspost/compress/flate.(*Writer).Close(0xc0320c2000, 0xc033692000, 0x8cc5)
        github.com/klauspost/compress/flate/deflate.go:801 +0x2d
```

**Comment by bronze1man** [comment]
> I managed to reproduce it with a test which indicates this should help out, but please do give feedback on whether it also helps you.

Yes, it works, the server is not crash after one hour. I will close this issues after the server is not crash after 24 hours.

**Comment by klauspost** [comment]
Cool. Seems like the `-race` test is timing out. When it's fixed I will merge the changes.

There will probably be a release within the next week when #216 is also merged.

**Comment by bronze1man** [comment]
Sorry, but it crashed from code #218 
```
panic: e.cur < 0: -2147281275

goroutine 78 [running]:
github.com/klauspost/compress/flate.(*fastEncL4).Encode(0xc05ab1e000, 0xc014570090, 0xc044928000, 0xffff, 0xffff)
	github.com/klauspost/compress/flate/level4.go:17 +0xaf0
github.com/klauspost/compress/flate.(*compressor).storeFast(0xc014570000)
	github.com/klauspost/compress/flate/deflate.go:590 +0x1c1
github.com/klauspost/compress/flate.(*compressor).write(0xc014570000, 0xc04fad3fee, 0x245f98, 0x126012, 0x113e5c0, 0xc03b9af5c0, 0xc03b9af5c0)
	github.com/klauspost/compress/flate/deflate.go:614 +0x81
github.com/klauspost/compress/flate.(*Writer).Write(0xc014570000, 0xc04f9b4000, 0x245f98, 0x246000, 0xc00057b568, 0x44b894, 0xc038d3a2e1)
	github.com/klauspost/compress/flate/deflate.go:781 +0x4b
```

**Comment by klauspost** [comment]
Hmmm... that is somewhat unexpected. I will see if I can hunt it down. Thanks for testing.

**Comment by klauspost** [comment]
Updated #218

**Comment by bronze1man** [comment]
The server is not crashed after 3 hours. I will close this issues after the server is not crash after 24 hours.

**Comment by bronze1man** [comment]
@klauspost you forgot to write the change log in README.md

**Comment by klauspost** [comment]
Yeah, I usually does that before release, unless I remember :)

**Comment by bronze1man** [comment]
Thanks, The server is not crash with this reason after 24 hours.
I think this problem have been fixed.
