### ISSUE TITLE
zstd: tests timing out on Fedora aarch64 builders

### ISSUE THREAD

**Issue by rathann** [klauspost/compress#356]
Could you increase the timeout in https://github.com/klauspost/compress/blob/master/zstd/encoder_test.go#L201 ? This test is timing out on Fedora aarch64 builders:
```
Testing    in: /builddir/build/BUILD/compress-1.12.1/_build/src
         PATH: /builddir/build/BUILD/compress-1.12.1/_build/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
       GOPATH: /builddir/build/BUILD/compress-1.12.1/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test -buildmode pie -compiler gc -ldflags " -X github.com/klauspost/compress/version=1.12.1 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  '"
      testing: github.com/klauspost/compress
github.com/klauspost/compress
testing: warning: no tests to run
PASS
ok  	github.com/klauspost/compress	0.004s
github.com/klauspost/compress/flate
PASS
ok  	github.com/klauspost/compress/flate	48.643s
github.com/klauspost/compress/fse
PASS
ok  	github.com/klauspost/compress/fse	1.069s
github.com/klauspost/compress/gzip
PASS
ok  	github.com/klauspost/compress/gzip	55.744s
github.com/klauspost/compress/huff0
PASS
ok  	github.com/klauspost/compress/huff0	3.852s
github.com/klauspost/compress/s2
PASS
ok  	github.com/klauspost/compress/s2	493.999s
github.com/klauspost/compress/zip
PASS
ok  	github.com/klauspost/compress/zip	134.596s
github.com/klauspost/compress/zlib
PASS
ok  	github.com/klauspost/compress/zlib	0.985s
github.com/klauspost/compress/zstd
2021/04/19 10:46:19 === Timeout, assuming deadlock ===
*** goroutine dump...
goroutine 41722 [running]:
github.com/klauspost/compress/zstd.timeout.func1(0x4024942180, 0x400092ad80)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/decoder_test.go:1491 +0xb8
created by github.com/klauspost/compress/zstd.timeout
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/decoder_test.go:1485 +0x70
goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0x402bdfa000, 0xaaaadafe4449, 0x15, 0xaaaadb136188, 0x607d5e01)
	/usr/lib/golang/src/testing/testing.go:1239 +0x238
testing.runTests.func1(0x4000116180)
	/usr/lib/golang/src/testing/testing.go:1511 +0x74
testing.tRunner(0x4000116180, 0x400006dcd8)
	/usr/lib/golang/src/testing/testing.go:1193 +0xdc
testing.runTests(0x4000124030, 0xaaaadb23d2a0, 0x2f, 0x2f, 0xc017762ab95f46e8, 0x8bb2d71de3, 0xaaaadb240e20, 0x400010ac30)
	/usr/lib/golang/src/testing/testing.go:1509 +0x284
testing.(*M).Run(0x4000142180, 0x0)
	/usr/lib/golang/src/testing/testing.go:1417 +0x1b4
github.com/klauspost/compress/zstd.TestMain(0x4000142180)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/zstd_test.go:13 +0x28
main.main()
	_testmain.go:187 +0x150
goroutine 41721 [chan receive]:
testing.(*T).Run(0x40035f2000, 0x4015ff0ee8, 0x11, 0x400356a030, 0x1)
	/usr/lib/golang/src/testing/testing.go:1239 +0x238
github.com/klauspost/compress/zstd.TestEncoderRegression(0x402bdfa000)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/encoder_test.go:214 +0x218
testing.tRunner(0x402bdfa000, 0xaaaadb136188)
	/usr/lib/golang/src/testing/testing.go:1193 +0xdc
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1238 +0x21c
goroutine 41724 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0x400010b450)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:215 +0x108
created by github.com/klauspost/compress/zstd.newBlockDec
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:118 +0x130
goroutine 41728 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0x400010b790)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:215 +0x108
created by github.com/klauspost/compress/zstd.newBlockDec
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:118 +0x130
goroutine 650787 [runnable]:
github.com/klauspost/compress/zstd.(*bestFastEncoder).Encode.func2(0x2895000028668, 0x133303538, 0x2894ffffda0e8, 0x0)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/enc_best.go:154 +0x148
github.com/klauspost/compress/zstd.(*bestFastEncoder).Encode(0x4024a00000, 0x40076140e0, 0x4007d22000, 0x28c00, 0x400)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/enc_best.go:186 +0x1714
github.com/klauspost/compress/zstd.(*Encoder).nextBlock.func1(0x0, 0x4007274168, 0x4007274120, 0x4003567400, 0x400, 0x400)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/encoder.go:260 +0x94
created by github.com/klauspost/compress/zstd.(*Encoder).nextBlock
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/encoder.go:247 +0x260
goroutine 646980 [chan receive]:
testing.(*T).Run(0x4005886000, 0x40035e6060, 0x13, 0x4005b060e0, 0x1)
	/usr/lib/golang/src/testing/testing.go:1239 +0x238
github.com/klauspost/compress/zstd.TestEncoderRegression.func1(0x40035f2000)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/encoder_test.go:236 +0x2c8
testing.tRunner(0x40035f2000, 0x400356a030)
	/usr/lib/golang/src/testing/testing.go:1193 +0xdc
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1238 +0x21c
goroutine 41746 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0x400010bad0)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:215 +0x108
created by github.com/klauspost/compress/zstd.newBlockDec
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:118 +0x130
goroutine 41726 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0x400010b5f0)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:215 +0x108
created by github.com/klauspost/compress/zstd.newBlockDec
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:118 +0x130
goroutine 650454 [semacquire]:
sync.runtime_Semacquire(0x4007274204)
	/usr/lib/golang/src/runtime/sema.go:56 +0x38
sync.(*WaitGroup).Wait(0x4007274204)
	/usr/lib/golang/src/sync/waitgroup.go:130 +0x74
github.com/klauspost/compress/zstd.(*Encoder).nextBlock(0x4007274120, 0x4008eecc00, 0x400, 0x0)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/encoder.go:170 +0x34
github.com/klauspost/compress/zstd.(*Encoder).Write(0x4007274120, 0x4008eed000, 0xd6f9c, 0xff000, 0x0, 0x0, 0xfff9c)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/encoder.go:154 +0x15c
github.com/klauspost/compress/zstd.TestEncoderRegression.func1.1(0x4005886000)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/encoder_test.go:256 +0x2c0
testing.tRunner(0x4005886000, 0x4005b060e0)
	/usr/lib/golang/src/testing/testing.go:1193 +0xdc
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1238 +0x21c
goroutine 41727 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0x400010b6c0)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:215 +0x108
created by github.com/klauspost/compress/zstd.newBlockDec
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:118 +0x130
goroutine 41723 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0x400010b380)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:215 +0x108
created by github.com/klauspost/compress/zstd.newBlockDec
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:118 +0x130
goroutine 41745 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0x400010ba00)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:215 +0x108
created by github.com/klauspost/compress/zstd.newBlockDec
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:118 +0x130
goroutine 41725 [chan receive, 2 minutes]:
github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0x400010b520)
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:215 +0x108
created by github.com/klauspost/compress/zstd.newBlockDec
	/builddir/build/BUILD/compress-1.12.1/_build/src/github.com/klauspost/compress/zstd/blockdec.go:118 +0x130
*** end
exit status 2
FAIL	github.com/klauspost/compress/zstd	168.813s
```

Suggested patch:
```diff
diff -up compress-1.12.1/zstd/encoder_test.go.orig compress-1.12.1/zstd/encoder_test.go
--- compress-1.12.1/zstd/encoder_test.go.orig   2021-04-14 09:49:47.000000000 +0000
+++ compress-1.12.1/zstd/encoder_test.go        2021-04-19 11:51:48.717177340 +0000
@@ -198,7 +198,7 @@ func TestEncoder_EncodeAllEncodeXML(t *t
 }

 func TestEncoderRegression(t *testing.T) {
-       defer timeout(2 * time.Minute)()
+       defer timeout(3 * time.Minute)()
        data, err := ioutil.ReadFile("testdata/comp-crashers.zip")
        if err != nil {
                t.Fatal(err)
```

With this patch applied, the tests complete successfully:
```
Testing    in: /builddir/build/BUILD/compress-1.12.1/_build/src
         PATH: /builddir/build/BUILD/compress-1.12.1/_build/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
       GOPATH: /builddir/build/BUILD/compress-1.12.1/_build:/usr/share/gocode
  GO111MODULE: off
      command: go test -buildmode pie -compiler gc -ldflags " -X github.com/klauspost/compress/version=1.12.1 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  '"
      testing: github.com/klauspost/compress
github.com/klauspost/compress
testing: warning: no tests to run
PASS
ok  	github.com/klauspost/compress	0.004s
github.com/klauspost/compress/flate
PASS
ok  	github.com/klauspost/compress/flate	34.525s
github.com/klauspost/compress/fse
PASS
ok  	github.com/klauspost/compress/fse	0.943s
github.com/klauspost/compress/gzip
PASS
ok  	github.com/klauspost/compress/gzip	74.396s
github.com/klauspost/compress/huff0
PASS
ok  	github.com/klauspost/compress/huff0	2.642s
github.com/klauspost/compress/s2
PASS
ok  	github.com/klauspost/compress/s2	227.304s
github.com/klauspost/compress/zip
PASS
ok  	github.com/klauspost/compress/zip	75.732s
github.com/klauspost/compress/zlib
PASS
ok  	github.com/klauspost/compress/zlib	0.761s
github.com/klauspost/compress/zstd
PASS
ok  	github.com/klauspost/compress/zstd	200.018s
github.com/klauspost/compress/zstd/internal/xxhash
PASS
ok  	github.com/klauspost/compress/zstd/internal/xxhash	0.007s
```

**Comment by klauspost** [comment]
@rathann Sure... PR added.
