### ISSUE TITLE
1.13.4 github.com/klauspost/compress/zip test crash with illegal instruction on s390x

### ISSUE THREAD

**Issue by rathann** [klauspost/compress#422]
While running the testsuite I'm getting the following crash:
```
github.com/klauspost/compress/zip
SIGILL: illegal instruction
PC=0x2aa0e131d4f m=3 sigcode=2
instruction bytes: 0x72 0x60 0x0 0x0 0xd 0xc2 0xe 0x0 0x0 0x0 0x40 0xa7 0x9 0x0 0x0 0xb9
goroutine 0 [idle]:
runtime.(*pallocData).findScavengeCandidate(0x3ff5dfef680, 0x108, 0x1, 0x1)
	/usr/lib/golang/src/runtime/mgcscavenge.go:894 +0x17f
runtime.(*pageAlloc).scavengeOne(0x2aa0e3aee88, {{0xc003400000}, {0xc003612000}}, 0x1000, 0x1)
	/usr/lib/golang/src/runtime/mgcscavenge.go:618 +0x14a
runtime.(*pageAlloc).scavenge(0x2aa0e3aee88, 0x1000, 0x1)
	/usr/lib/golang/src/runtime/mgcscavenge.go:413 +0x66
runtime.bgscavenge.func2()
	/usr/lib/golang/src/runtime/mgcscavenge.go:304 +0xc0
runtime.systemstack()
	/usr/lib/golang/src/runtime/asm_s390x.s:276 +0x6c
goroutine 4 [running]:
runtime.systemstack_switch()
	/usr/lib/golang/src/runtime/asm_s390x.s:239 +0x10 fp=0xc00003bf80 sp=0xc00003bf78 pc=0x2aa0e17c0f0
runtime.bgscavenge()
	/usr/lib/golang/src/runtime/mgcscavenge.go:292 +0x14c fp=0xc00003bfd8 sp=0xc00003bf80 pc=0x2aa0e13083c
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_s390x.s:755 +0x2 fp=0xc00003bfd8 sp=0xc00003bfd8 pc=0x2aa0e17e3f2
created by runtime.gcenable
	/usr/lib/golang/src/runtime/mgc.go:182 +0x88
goroutine 1 [chan receive]:
testing.tRunner.func1(0xc000086ea0)
	/usr/lib/golang/src/testing/testing.go:1225 +0x4b8
testing.tRunner(0xc000086ea0, 0xc0000a3d50)
	/usr/lib/golang/src/testing/testing.go:1265 +0x14c
testing.runTests(0xc0000ae018, {0x2aa0e3717e0, 0x22, 0x22}, {0xc03fb3fe5200e9f6, 0x8bb2d02507, 0x2aa0e38b420})
	/usr/lib/golang/src/testing/testing.go:1596 +0x4c2
testing.(*M).Run(0xc0000fa000)
	/usr/lib/golang/src/testing/testing.go:1504 +0x514
main.main()
	_testmain.go:119 +0x190
goroutine 293 [runnable]:
unicode/utf8.DecodeRuneInString({0xc0000dd807, 0xa7f8})
	/usr/lib/golang/src/unicode/utf8/utf8.go:199 +0x276
github.com/klauspost/compress/zip.detectUTF8({0xc0000d8000, 0xffff})
	/builddir/build/BUILD/compress-1.13.4/_build/src/github.com/klauspost/compress/zip/writer.go:254 +0x82
github.com/klauspost/compress/zip.(*Writer).CreateHeader(0xc000064060, 0xc0008ec630)
	/builddir/build/BUILD/compress-1.13.4/_build/src/github.com/klauspost/compress/zip/writer.go:306 +0x154
github.com/klauspost/compress/zip.TestZip64LargeDirectory.func1.1(0xc000064060)
	/builddir/build/BUILD/compress-1.13.4/_build/src/github.com/klauspost/compress/zip/zip_test.go:532 +0x210
github.com/klauspost/compress/zip.generatesZip64(0xc000116820, 0xc00105a000)
	/builddir/build/BUILD/compress-1.13.4/_build/src/github.com/klauspost/compress/zip/zip_test.go:456 +0x1b6
github.com/klauspost/compress/zip.TestZip64LargeDirectory.func2(0xc000116820)
	/builddir/build/BUILD/compress-1.13.4/_build/src/github.com/klauspost/compress/zip/zip_test.go:548 +0x66
testing.tRunner(0xc000116820, 0xc001168060)
	/usr/lib/golang/src/testing/testing.go:1259 +0xf8
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1306 +0x3da
goroutine 254 [chan receive]:
testing.tRunner.func1(0xc00015ba00)
	/usr/lib/golang/src/testing/testing.go:1225 +0x4b8
testing.tRunner(0xc00015ba00, 0x2aa0e2b7878)
	/usr/lib/golang/src/testing/testing.go:1265 +0x14c
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1306 +0x3da
goroutine 294 [runnable]:
unicode/utf8.DecodeRuneInString({0xc0001718eb, 0xa714})
	/usr/lib/golang/src/unicode/utf8/utf8.go:199 +0x276
github.com/klauspost/compress/zip.detectUTF8({0xc00016c000, 0xffff})
	/builddir/build/BUILD/compress-1.13.4/_build/src/github.com/klauspost/compress/zip/writer.go:254 +0x82
github.com/klauspost/compress/zip.(*Writer).CreateHeader(0xc000064240, 0xc000e7ccf0)
	/builddir/build/BUILD/compress-1.13.4/_build/src/github.com/klauspost/compress/zip/writer.go:306 +0x154
github.com/klauspost/compress/zip.TestZip64LargeDirectory.func1.1(0xc000064240)
	/builddir/build/BUILD/compress-1.13.4/_build/src/github.com/klauspost/compress/zip/zip_test.go:532 +0x210
github.com/klauspost/compress/zip.generatesZip64(0xc0001169c0, 0xc0000ae030)
	/builddir/build/BUILD/compress-1.13.4/_build/src/github.com/klauspost/compress/zip/zip_test.go:456 +0x1b6
github.com/klauspost/compress/zip.TestZip64LargeDirectory.func3(0xc0001169c0)
	/builddir/build/BUILD/compress-1.13.4/_build/src/github.com/klauspost/compress/zip/zip_test.go:554 +0x66
testing.tRunner(0xc0001169c0, 0xc0011680a0)
	/usr/lib/golang/src/testing/testing.go:1259 +0xf8
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1306 +0x3da
r0   0x37	r1   0xff
r2   0x1	r3   0xfffffffffffffff7
r4   0x4	r5   0x109
r6   0x37	r7   0x3ff5dfef6e0
r8   0x3ff5dfef000	r9   0x680
r10  0x0	r11  0x3ff5d7ed870
r12  0xc00003bfc0	r13  0xc000000ea0
r14  0x2aa0e131d1e	r15  0x3ff5d7eccc0
pc   0x2aa0e131d4f	link 0x2aa0e131d1e
exit status 2
FAIL	github.com/klauspost/compress/zip	26.488s
```

This is happening on Fedora rawhide only. Compared to earlier releases, the Golang package was updated to 1.17, among others. With 1.16.6 in F35 the test succeeds. There's also a new glibc (2.35 pre-release vs. 2.34). Bug in Golang, perhaps?

**Comment by klauspost** [comment]
Yes, it seems like a compiler bug since we are deep into the stdlib and there is no assembly in "zip" anyway.

**Comment by klauspost** [comment]
I would report this to https://github.com/golang/go/issues

I will keep this issue open until it is confirmed.

**Comment by klauspost** [comment]
@rathann If you report it upstream feel free to reference this issue.

**Comment by rathann** [comment]
Strangely enough, I can't reproduce this any more. I'll report it both to Fedora maintainer and upstream and link here if I manage to reproduce it again. Sorry for the noise.

**Comment by klauspost** [comment]
@rathann Since it is in Garbage Collection, it probably is random where/when it occurs. I would report it anyway.
