### ISSUE TITLE
goleak: Errors on successful test run: found unexpected goroutines

### ISSUE THREAD

**Issue by 3AceShowHand** [klauspost/compress#451]
Our CI service found a potential goroutine leak, please take a look.
```
[2021-11-18T03:11:20.345Z] goleak: Errors on successful test run: found unexpected goroutines:
[2021-11-18T03:11:20.345Z] [Goroutine 307 in state chan receive, with github.com/klauspost/compress/zstd.(*blockDec).startDecoder on top of the stack:
[2021-11-18T03:11:20.345Z] goroutine 307 [chan receive]:
[2021-11-18T03:11:20.345Z] github.com/klauspost/compress/zstd.(*blockDec).startDecoder(0xc0010a1040)
[2021-11-18T03:11:20.345Z] 	/nfs/cache/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:212 +0xd6
[2021-11-18T03:11:20.345Z] created by github.com/klauspost/compress/zstd.newBlockDec
[2021-11-18T03:11:20.345Z] 	/nfs/cache/mod/github.com/klauspost/compress@v1.13.6/zstd/blockdec.go:118 +0x1b3
[2021-11-18T03:11:20.345Z] 
[2021-11-18T03:11:20.345Z]  Goroutine 308 in state chan receive, with github.com/klauspost/compress/zstd.(*blockDec).startDecoder on top of the stack:
[2021-11-18T03:11:20.345Z] goroutine 308 [chan receive]:
```

https://github.com/pingcap/ticdc/pull/3508

**Comment by klauspost** [comment]
@3AceShowHand Make sure all decoders are [closed](https://pkg.go.dev/github.com/klauspost/compress/zstd#Decoder.Close).
