### ISSUE TITLE
zstd: Crash in executeSimple_amd64

### ISSUE THREAD

**Issue by klauspost** [klauspost/compress#549]
```
unexpected fault address 0xbff3f1c3a9
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xbff3f1c3a9 pc=0x3d7550]

goroutine 15 [running]:
runtime.throw({0x404429, 0x1c24e2c8900})
	runtime/panic.go:1198 +0x76 fp=0xc000087a10 sp=0xc0000879e0 pc=0x2e48d6
runtime.sigpanic()
	runtime/signal_windows.go:260 +0x10c fp=0xc000087a58 sp=0xc000087a10 pc=0x2f76ec
github.com/klauspost/compress/zstd.sequenceDecs_executeSimple_amd64(0xc000087b08)
	github.com/klauspost/compress/zstd/seqdec_amd64.s:662 +0xf0 fp=0xc000087a70 sp=0xc000087a58 pc=0x3d7550
github.com/klauspost/compress/zstd.(*sequenceDecs).executeSimple(0xc000087e60, {0xc0000e4c00, 0x2c51cf, 0x51d1e0}, {0xc000128000, 0x0, 0xc000087c48})
	e:/gopath/src/github.com/klauspost/compress/zstd/seqdec_amd64.go:146 +0x350 fp=0xc000087b98 sp=0xc000087a70 pc=0x3d4e10
github.com/klauspost/compress/zstd.(*sequenceDecs).execute(0x0, {0xc0000e4c00, 0xc000087ce0, 0x2ba305}, {0xc000128000, 0x3e8740, 0x3fa400})
	e:/gopath/src/github.com/klauspost/compress/zstd/seqdec.go:105 +0x31a fp=0xc000087ca8 sp=0xc000087b98 pc=0x3d089a
github.com/klauspost/compress/zstd.(*blockDec).executeSequences(0xc00010c360, 0xc000087e58)
	e:/gopath/src/github.com/klauspost/compress/zstd/blockdec.go:695 +0x1df fp=0xc000087cf0 sp=0xc000087ca8 pc=0x3942bf
github.com/klauspost/compress/zstd.(*Decoder).startStreamDecoder.func3()
	e:/gopath/src/github.com/klauspost/compress/zstd/decoder.go:806 +0x8d6 fp=0xc000087fe0 sp=0xc000087cf0 pc=0x3a1876
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc000087fe8 sp=0xc000087fe0 pc=0x30fec1
created by github.com/klauspost/compress/zstd.(*Decoder).startStreamDecoder
	e:/gopath/src/github.com/klauspost/compress/zstd/decoder.go:739 +0x3a8
```

Repro: [03c8111bafdf29774aee4d803e8e5b65381171c7.gz](https://github.com/klauspost/compress/files/8410347/03c8111bafdf29774aee4d803e8e5b65381171c7.gz)

@WojciechMula 

```
copy_4_dword:
	TESTQ $0x00000004, R11
	JZ    copy_4_qword
->>	MOVL  (R14)(R12*1), R13
	MOVL  R13, (BX)(R12*1)
	ADDQ  $0x04, R12
```

**Comment by WojciechMula** [comment]
Thanks, I will check it.

**Comment by klauspost** [comment]
@WojciechMula This reproduces the error fairly reliable by forcing history to be a 0 pointer:

```
	ctx := executeAsmContext{
		seqs:        seqs,
		seqIndex:    0,
		out:         out,
		history:     hist,
		outPosition: t,
		litPosition: 0,
		literals:    s.literals,
		windowSize:  s.windowSize,
	}
	if len(hist) == 0 {
		ctx.history = nil
	}
```

It seems like history copying can be triggered even if there is no history.

```
unexpected fault address 0xffffffffffffffd9
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffd9 pc=0x267c20]

goroutine 10 [running]:
runtime.throw({0x295429, 0x0})
	runtime/panic.go:1198 +0x76 fp=0xc00011ba10 sp=0xc00011b9e0 pc=0x1748d6
runtime.sigpanic()
	runtime/signal_windows.go:260 +0x10c fp=0xc00011ba58 sp=0xc00011ba10 pc=0x1876ec
github.com/klauspost/compress/zstd.sequenceDecs_executeSimple_amd64(0xc00011bb08)
	github.com/klauspost/compress/zstd/seqdec_amd64.s:1149 +0xc0 fp=0xc00011ba70 sp=0xc00011ba58 pc=0x267c20
github.com/klauspost/compress/zstd.(*sequenceDecs).executeSimple(0xc00011be60, {0xc0000f0180, 0x28f660, 0xc000075a01}, {0xc0000f3800, 0x0, 0x0})
	e:/gopath/src/github.com/klauspost/compress/zstd/seqdec_amd64.go:167 +0x3b7 fp=0xc00011bb98 sp=0xc00011ba70 pc=0x264f97
github.com/klauspost/compress/zstd.(*sequenceDecs).execute(0x0, {0xc0000f0180, 0xc00011bce0, 0x14a305}, {0xc0000f3800, 0x279740, 0x0})
	e:/gopath/src/github.com/klauspost/compress/zstd/seqdec.go:105 +0x31a fp=0xc00011bca8 sp=0xc00011bb98 pc=0x26089a
github.com/klauspost/compress/zstd.(*blockDec).executeSequences(0xc00010e120, 0xc00011be58)
	e:/gopath/src/github.com/klauspost/compress/zstd/blockdec.go:695 +0x1df fp=0xc00011bcf0 sp=0xc00011bca8 pc=0x2242bf
github.com/klauspost/compress/zstd.(*Decoder).startStreamDecoder.func3()
	e:/gopath/src/github.com/klauspost/compress/zstd/decoder.go:806 +0x8d6 fp=0xc00011bfe0 sp=0xc00011bcf0 pc=0x231876
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc00011bfe8 sp=0xc00011bfe0 pc=0x19fec1
created by github.com/klauspost/compress/zstd.(*Decoder).startStreamDecoder
	e:/gopath/src/github.com/klauspost/compress/zstd/decoder.go:739 +0x3a8 
```

**Comment by klauspost** [comment]
```
		TESTQ(ll, ll)
		JZ(LabelRef("copy_history"))
```		

... skips the offset check. Sending a PR.
