### ISSUE TITLE
Another sequenceDecs_executeSimple_amd64 crash

### ISSUE THREAD

**Issue by klauspost** [klauspost/compress#552]
```
unexpected fault address 0xc00039e000
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xc00039e000 pc=0xb57be7]

goroutine 9082 [running]:
runtime.throw({0xb85429, 0xc00026da98})
	runtime/panic.go:1198 +0x76 fp=0xc00026da10 sp=0xc00026d9e0 pc=0xa648d6
runtime.sigpanic()
	runtime/signal_windows.go:260 +0x10c fp=0xc00026da58 sp=0xc00026da10 pc=0xa776ec
github.com/klauspost/compress/zstd.sequenceDecs_executeSimple_amd64(0xc00026db08)
	github.com/klauspost/compress/zstd/seqdec_amd64.s:1121 +0x67 fp=0xc00026da70 sp=0xc00026da58 pc=0xb57be7
github.com/klauspost/compress/zstd.(*sequenceDecs).executeSimple(0xc00026de60, {0xc0001a3800, 0xa6d600, 0xc00024fb00}, {0xc000280000, 0x598, 0xa8db95})
	e:/gopath/src/github.com/klauspost/compress/zstd/seqdec_amd64.go:164 +0x350 fp=0xc00026db98 sp=0xc00026da70 pc=0xb54fb0
github.com/klauspost/compress/zstd.(*sequenceDecs).execute(0xc00028dbc0, {0xc0001a3800, 0xc00026dce0, 0xa35bb8}, {0xc000280000, 0xc00026dd50, 0xc000280001})
	e:/gopath/src/github.com/klauspost/compress/zstd/seqdec.go:105 +0x31a fp=0xc00026dca8 sp=0xc00026db98 pc=0xb5089a
github.com/klauspost/compress/zstd.(*blockDec).executeSequences(0xc00024fb00, 0xc00026de58)
	e:/gopath/src/github.com/klauspost/compress/zstd/blockdec.go:695 +0x1df fp=0xc00026dcf0 sp=0xc00026dca8 pc=0xb142bf
github.com/klauspost/compress/zstd.(*Decoder).startStreamDecoder.func3()
	e:/gopath/src/github.com/klauspost/compress/zstd/decoder.go:806 +0x8d6 fp=0xc00026dfe0 sp=0xc00026dcf0 pc=0xb21876
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc00026dfe8 sp=0xc00026dfe0 pc=0xa8fec1
created by github.com/klauspost/compress/zstd.(*Decoder).startStreamDecoder
	e:/gopath/src/github.com/klauspost/compress/zstd/decoder.go:739 +0x3a8

... 
 
copy_1:
-->	MOVUPS (SI)(R14*1), X0
	MOVUPS X0, (BX)(R14*1)
	ADDQ   $0x10, R14
	CMPQ   R14, R13
	JB     copy_1
```

**Comment by klauspost** [comment]
Literals cannot overread by default @WojciechMula - I suspect that is the issue.
