### ISSUE TITLE
crash sequenceDecs_decodeSync_bmi2

### ISSUE THREAD

**Issue by klauspost** [klauspost/compress#562]
```
unexpected fault address 0xc0001ee000
fatal error: fault
[signal 0xc0000005 code=0x1 addr=0xc0001ee000 pc=0xca974e]

goroutine 6 [running]:
runtime.throw({0xcd6449, 0x39})
	runtime/panic.go:1198 +0x76 fp=0xc000087868 sp=0xc000087838 pc=0xbb48d6
runtime.sigpanic()
	runtime/signal_windows.go:260 +0x10c fp=0xc0000878b0 sp=0xc000087868 pc=0xbc76ec
github.com/klauspost/compress/zstd.sequenceDecs_decodeSync_bmi2(0xc0000b2050, 0xc00001e0c0, 0xc000087990)
	github.com/klauspost/compress/zstd/seqdec_amd64.s:2392 +0x56e fp=0xc0000878f8 sp=0xc0000878b0 pc=0xca974e
github.com/klauspost/compress/zstd.(*sequenceDecs).decodeSyncSimple(0xc0000b2050, {0x0, 0x0, 0x216d85c0108})
	e:/gopath/src/github.com/klauspost/compress/zstd/seqdec_amd64.go:76 +0x36b fp=0xc000087a88 sp=0xc0000878f8 pc=0xca470b
github.com/klauspost/compress/zstd.(*sequenceDecs).decodeSync(0xc0000b2050, {0x0, 0xeb8, 0x0})
	e:/gopath/src/github.com/klauspost/compress/zstd/seqdec.go:206 +0x85 fp=0xc000087bf8 sp=0xc000087a88 pc=0xca16c5
github.com/klauspost/compress/zstd.(*blockDec).decodeCompressed(0xc0000b0000, 0xc0000b2048)
	e:/gopath/src/github.com/klauspost/compress/zstd/blockdec.go:498 +0x25b fp=0xc000087c50 sp=0xc000087bf8 pc=0xc6279b
github.com/klauspost/compress/zstd.(*blockDec).decodeBuf(0xc0000b0000, 0xc0000b2048)
	e:/gopath/src/github.com/klauspost/compress/zstd/blockdec.go:262 +0x445 fp=0xc000087d08 sp=0xc000087c50 pc=0xc5fb25
github.com/klauspost/compress/zstd.(*frameDec).runDecoder(0xc0000b2000, {0xc00017a000, 0x0, 0x0}, 0xc0000b0000)
	e:/gopath/src/github.com/klauspost/compress/zstd/framedec.go:338 +0x1d0 fp=0xc000087db8 sp=0xc000087d08 pc=0xc98390
github.com/klauspost/compress/zstd.(*Decoder).DecodeAll(0xc00009c000, {0x216fdd30000, 0xed0, 0xed0}, {0x0, 0x0, 0x0})
	e:/gopath/src/github.com/klauspost/compress/zstd/decoder.go:376 +0xa4e fp=0xc000087f80 sp=0xc000087db8 pc=0xc6da0e
github.com/klauspost/compress-fuzz/zstd.FuzzDecompress.func1()
	e:/gopath/src/github.com/klauspost/compress-fuzz/zstd/fuzz_decompress.go:30 +0x68 fp=0xc000087fe0 sp=0xc000087f80 pc=0xcaee68
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc000087fe8 sp=0xc000087fe0 pc=0xbdfec1
created by github.com/klauspost/compress-fuzz/zstd.FuzzDecompress
	e:/gopath/src/github.com/klauspost/compress-fuzz/zstd/fuzz_decompress.go:29 +0x431
```
Input: [5442d1febd1324b35c667ea502d93dc531f3f83d.gz](https://github.com/klauspost/compress/files/8532276/5442d1febd1324b35c667ea502d93dc531f3f83d.gz)

Current master

@WojciechMula Could you take a look?

**Comment by klauspost** [comment]
Root cause could easily be the same as #563

**Comment by WojciechMula** [comment]
> Root cause could easily be the same as #563

You were right. I added the file from this issue to the regression set.
