### ISSUE TITLE
crash, decoder.go:322

### ISSUE THREAD

**Issue by klauspost** [klauspost/compress#563]
```
unexpected fault address 0xffffffffffffffff
fatal error: fault
[signal 0xc0000005 code=0x0 addr=0xffffffffffffffff pc=0x1de03d]

goroutine 28714 [running]:
runtime.throw({0x246449, 0x3cf})
	runtime/panic.go:1198 +0x76 fp=0xc0000dba28 sp=0xc0000db9f8 pc=0x1248d6
runtime.sigpanic()
	runtime/signal_windows.go:260 +0x10c fp=0xc0000dba70 sp=0xc0000dba28 pc=0x1376ec
github.com/klauspost/compress/zstd.(*Decoder).DecodeAll.func1()
	e:/gopath/src/github.com/klauspost/compress/zstd/decoder.go:322 +0xfd fp=0xc0000dba98 sp=0xc0000dba70 pc=0x1de03d
runtime.deferCallSave(0xc0000dbba0, 0xc0000dbe78)
	runtime/panic.go:950 +0x82 fp=0xc0000dbaa8 sp=0xc0000dba98 pc=0x124062
runtime.runOpenDeferFrame(0xddf5, 0xc000092050)
	runtime/panic.go:889 +0x27b fp=0xc0000dbb28 sp=0xc0000dbaa8 pc=0x1239fb
panic({0x22f4c0, 0x2743e0})
	runtime/panic.go:1038 +0x215 fp=0xc0000dbbe8 sp=0xc0000dbb28 pc=0x1242d5
runtime.growslice(0xc0000b0240, {0xa2e3d9a2a2a28cd9, 0x22a920, 0x2030001}, 0xc0000dbcf8)
	runtime/slice.go:256 +0x565 fp=0xc0000dbc50 sp=0xc0000dbbe8 pc=0x138225
github.com/klauspost/compress/zstd.(*history).appendKeep(...)
	e:/gopath/src/github.com/klauspost/compress/zstd/history.go:118
github.com/klauspost/compress/zstd.(*blockDec).decodeBuf(0xc0000b0240, 0xc000532648)
	e:/gopath/src/github.com/klauspost/compress/zstd/blockdec.go:270 +0x5c6 fp=0xc0000dbd08 sp=0xc0000dbc50 pc=0x1cfca6
github.com/klauspost/compress/zstd.(*frameDec).runDecoder(0xc000532600, {0xc0002fe000, 0x0, 0x1c60}, 0xc0000b0240)
	e:/gopath/src/github.com/klauspost/compress/zstd/framedec.go:338 +0x1d0 fp=0xc0000dbdb8 sp=0xc0000dbd08 pc=0x208390
github.com/klauspost/compress/zstd.(*Decoder).DecodeAll(0xc00009c0e0, {0x296ed860000, 0x28bd5, 0x28bd5}, {0x0, 0x0, 0x0})
	e:/gopath/src/github.com/klauspost/compress/zstd/decoder.go:376 +0xa4e fp=0xc0000dbf80 sp=0xc0000dbdb8 pc=0x1dda0e
github.com/klauspost/compress-fuzz/zstd.FuzzDecompress.func1()
	e:/gopath/src/github.com/klauspost/compress-fuzz/zstd/fuzz_decompress.go:30 +0x68 fp=0xc0000dbfe0 sp=0xc0000dbf80 pc=0x21ee68
runtime.goexit()
	runtime/asm_amd64.s:1581 +0x1 fp=0xc0000dbfe8 sp=0xc0000dbfe0 pc=0x14fec1
created by github.com/klauspost/compress-fuzz/zstd.FuzzDecompress
	e:/gopath/src/github.com/klauspost/compress-fuzz/zstd/fuzz_decompress.go:29 +0x431
```

Looks like some sort of corruption.

Input: [05d57667c86a14c61262c925d95d398c6e921012.gz](https://github.com/klauspost/compress/files/8532300/05d57667c86a14c61262c925d95d398c6e921012.gz)

@WojciechMula could you check it out?

**Comment by klauspost** [comment]
@WojciechMula I suspect we are writing more than cap of the output slice.

Are there checks to abort as soon as we reach the cap or max block size?

**Comment by WojciechMula** [comment]
I'm working on this. BTW, for that file the C implementation prints:

```shell
$ zstd --test 05d57667c86a14c61262c925d95d398c6e921012 
c925d95d398c6e921012 : 0 MB...     c925d95d398c6e921012 : Decoding error (36) : Destination buffer is too small
```

**Comment by WojciechMula** [comment]
> Are there checks to abort as soon as we reach the cap or max block size?

No, I removed the runtime check when I was cleaning up the retrying functionality. Restored the test.

**Comment by klauspost** [comment]
Fixed 👍🏼 Fuzz tests now running for 30mins, no problems so far.
