### ISSUE TITLE
zlib decode is not "All heap memory allocations eliminated"

### ISSUE THREAD

**Issue by bronze1man** [klauspost/compress#80]
It only have one alloc left when I reuse the reader object:
* https://github.com/klauspost/compress/blob/master/zlib/reader.go#L176

```
tracealloc(0xc4205fe030, 0x10, adler32.digest)
goroutine 5 [running]:
runtime.mallocgc(0x10, 0x1162cc0, 0x1, 0x0)
	/usr/local/go/src/runtime/malloc.go:783 +0x4d3 fp=0xc4205ebc38 sp=0xc4205ebb90 pc=0x100fa63
runtime.newobject(0x1162cc0, 0x126c6a0)
	/usr/local/go/src/runtime/malloc.go:840 +0x38 fp=0xc4205ebc68 sp=0xc4205ebc38 pc=0x100ffc8
hash/adler32.New(...)
	/usr/local/go/src/hash/adler32/adler32.go:38
github.com/bronze1man/kmg/vendor/github.com/klauspost/compress/zlib.(*reader).Reset(0xc420074190, 0x126c6a0, 0xc420074140, 0x0, 0x0, 0x0, 0xfd8dd378fc5066be, 0xc4200602f8)
	/xxx/src/github.com/bronze1man/kmg/vendor/github.com/klauspost/compress/zlib/reader.go:176 +0x3df fp=0xc4205ebda0 sp=0xc4205ebc68 pc=0x113bc6f
```

**Comment by klauspost** [comment]
Thanks for reporting!  I haven't really looked into zlib.

**Comment by bronze1man** [comment]
The master branch do not solve this problem.The alloc will happened in the similar place.
https://github.com/klauspost/compress/blob/master/zlib/reader.go#L131
https://github.com/klauspost/compress/blob/master/zlib/reader.go#L177

You should add a test to verify it do not have alloc.
